Repository nextcloud/cdav-library, pull requests merged in 2018-10, with the labels that each got.

#13 Add eslinting to the lib
  .eslintrc.js
  Makefile
  package-lock.json
  package.json
  src/debug.js
  src/index.js
  src/models/addressBook.js
  src/models/addressBookHome.js
  src/models/calendar.js
  src/models/calendarHome.js
  src/models/davCollection.js
  src/models/davCollectionPublishable.js
  src/models/davCollectionShareable.js
  src/models/davEvent.js
  src/models/davEventListener.js
  src/models/davObject.js
  src/models/scheduleInbox.js
  src/models/scheduleOutbox.js
  src/models/subscription.js
  src/models/vcard.js
  src/models/vobject.js
  src/parser/addressbookParser.js
  src/parser/calendarParser.js
  src/parser/davCollectionParser.js
  src/parser/davCollectionPublishableParser.js
  src/parser/davCollectionShareableParser.js
  src/propset/addressBookPropSet.js
  src/propset/calendarPropSet.js
  src/propset/davCollectionPropSet.js
  src/request.js
  src/utility/stringUtility.js
  src/utility/xmlUtility.js
  webpack.common.js
Labels: enhancement

#16 add babel to ensure compatibility with legacy browsers
  .babelrc.js
  dist/dist.js
  dist/dist.js.map
  package-lock.json
  package.json
  webpack.common.js
  webpack.dev.js
Labels: 2. developing, bug, high

#29 fix documentation of options properties for DavClient constructor
  .gitignore
  src/index.js
Labels: 3. to review
