Repository nextcloud/cdav-library, pull requests merged in 2021-08, with the labels that each got.

#524 Add missing artifacts for #520
  dist/dist.js
  dist/dist.js.map
Labels: bug, 4. to release

#528 Add commit checks workflow
  .github/workflows/fixup.yml
Labels: 3. to review

#534 Fetch principal user language
  dist/dist.js
  dist/dist.js.map
  src/models/principal.js
  src/parser.js
  test/unit/models/principalTest.js
Labels: 3. to review

#540 Use own object's content type for request when updating it
  dist/dist.js
  dist/dist.js.map
  src/models/davObject.js
  test/unit/models/davObjectTest.js
Labels: bug, 3. to review
