Repository nextcloud/cdav-library, pull requests merged in 2021-12, with the labels that each got.

#600 Prepare for publishing to npm
  .gitignore
  dist/dist.js
  dist/dist.js.map
  package.json
Labels: enhancement, 3. to review

#601 Remove private field from package.json
  package-lock.json
  package.json
Labels: bug, 3. to review

#606 Rename `master` to `main`
  .github/workflows/build.yml
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint.yml
  .github/workflows/npm-test.yml
Labels: 3. to review
