Repository nextcloud/cdav-library, pull requests merged in 2021-06, with the labels that each got.

#480 Allow additional headers for DAV collection DELETE requests
  dist/dist.js
  dist/dist.js.map
  src/models/davCollection.js
  test/unit/models/davCollectionTest.js
Labels: 3. to review, enhancement

#481 Request the calendar trash bin duration prop
  dist/dist.js
  dist/dist.js.map
  src/models/calendar.js
  src/parser.js
Labels: 3. to review, enhancement

#482 Make the caldav trash bin's retention duration a real property
  dist/dist.js
  dist/dist.js.map
  src/models/calendarTrashBin.js
Labels: 3. to review

#462 Fix handling of empty resourcetype
  src/models/davCollection.js
Labels: 3. to review, bug

#489 Update dependencies
  package-lock.json
Labels: 3. to review

#492 Implement deleted calendar collection
  src/models/calendarHome.js
  src/models/deletedCalendar.js
Labels: 3. to review, enhancement

#498 Add built javascript files for #492
  dist/dist.js
  dist/dist.js.map
Labels: 3. to review

#503 Use ISO8601 timestamps for the CalDAV trashbin
  dist/dist.js
  dist/dist.js.map
  src/parser.js
Labels: 3. to review
