Repository nextcloud/cdav-library, pull requests merged in 2024-09, with the labels that each got.

#913 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#917 chore(CI): Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#914 chore: update workflows from templates
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, 3. to review, automated

#918 chore: Define code owners
  .github/CODEOWNERS
Labels: 3. to review

#920 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
