Repository nextcloud/cdav-library, pull requests merged in 2024-02, with the labels that each got.

#871 feat: implement updating a principal's schedule-default-calendar-URL
  src/models/principal.js
  src/propset/principalPropSet.js
  test/unit/models/principalTest.js
  test/unit/propset/principalPropSet.js
Labels: enhancement, 3. to review

#866 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
Labels: dependencies, 3. to review, automated

#860 Update npm and node engines versions
  package-lock.json
  package.json
Labels: dependencies

#873 chore(deps-dev): drop obsolete eslint plugins
  package-lock.json
  package.json
Labels: 3. to review, technical debt
