Repository nextcloud/cdav-library, pull requests merged in 2024-07, with the labels that each got.

#908 feat: expose scheduling transparency property
  src/models/calendar.js
  src/propset/calendarPropSet.js
Labels: 3. to review

#907 chore: update workflows from templates
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/fixup.yml
  .github/workflows/npm-audit-fix.yml
Labels: dependencies, 3. to review, automated

#910 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
