Repository nextcloud/cdav-library, pull requests merged in 2024-06, with the labels that each got.

#891 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#890 feat: find principal collections
  src/index.js
  src/models/principal.js
Labels: enhancement, 3. to review

#904 feat: bundle with vite and provide an additional esm bundle
  .eslintrc.cjs
  babel.config.cjs
  karma.conf.cjs
  package-lock.json
  package.json
  vite.config.js
Labels: enhancement, 3. to review

#906 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review
