Repository nextcloud/cdav-library, pull requests merged in 2025-05, with the labels that each got.

#949 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#954 feat: send custom default headers with each request
  src/index.js
  src/request.js
  test/unit/requestTest.js
Labels: enhancement, 3. to review

#953 fix: send OPTIONS request to acquire advertised DAV features
  src/index.js
  src/request.js
  test/unit/requestTest.js
Labels: bug, 3. to review
