Repository nextcloud/cdav-library, pull requests merged in 2025-03, with the labels that each got.

#931 build: migrate tests from Karama and Jasmine to Vitest
  .github/workflows/npm-test.yml
  babel.config.cjs
  karma.conf.cjs
  package-lock.json
  package.json
  test/unit/debugTest.js
  test/unit/indexTest.js
  test/unit/models/addressBookHomeTest.js
  test/unit/models/addressBookTest.js
  test/unit/models/calendarHomeTest.js
  test/unit/models/calendarTest.js
  test/unit/models/davCollectionPublishableTest.js
  test/unit/models/davCollectionShareableTest.js
  test/unit/models/davCollectionTest.js
  test/unit/models/davEventListenerTest.js
  test/unit/models/davEventTest.js
  test/unit/models/davObjectTest.js
  test/unit/models/principalTest.js
  test/unit/models/scheduleInboxTest.js
  test/unit/models/scheduleOutboxTest.js
  test/unit/models/subscriptionTest.js
  test/unit/models/vcardTest.js
  test/unit/models/vobjectTest.js
  test/unit/parserTest.js
  test/unit/propset/addressBookPropSetTest.js
  test/unit/propset/calendarPropSetTest.js
  test/unit/propset/davCollectionPropSetTest.js
  test/unit/propset/principalPropSet.js
  test/unit/propset/scheduleInboxPropSetTest.js
  test/unit/requestTest.js
  test/unit/utility/namespaceUtilityTest.js
  test/unit/utility/stringUtilityTest.js
  test/unit/utility/xmlUtilityTest.js
  vite.config.js
  webpack.common.js
  webpack.dev.js
  webpack.prod.js
Labels: 4. to release, technical debt

#932 [main] Fix npm audit
  package-lock.json
Labels: dependencies, 3. to review

#937 feat: serialize namespaced attributes consistently across browsers
  .github/workflows/npm-test.yml
  src/utility/xmlUtility.js
  test/unit/utility/xmlUtilityTest.js
  vite.config.js
Labels: enhancement, 4. to release
